### ISSUE TITLE
Crash.

### ISSUE THREAD

**Issue by UltimateBoi** [kr45732/rust-query-api#3]
When i try to run it in railway (with all env in it) it errors with this:
`Loggers Created
Reading config
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error { kind: ConfigParse, cause: Some(UnknownOption("${{postgres://avnadmin:censored@censored:censored/skyblock?sslmode")) }', src/main.rs:106:14
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Aborted (core dumped)`

**Comment by kr45732** [comment]
If you want to use SSL for the postgres connection, the mode must be specified as one of the following:
- `sslmode=disable`: Do not use TLS
- `sslmode=prefer`: Attempt to connect with TLS but allow sessions without
- `sslmode=require`: Require the use of TLS

It is currently erroring because you haven't specified the mode. You can also remove the `sslmode` parameter if you don't want to use SSL.

**Comment by UltimateBoi** [comment]
How and where do i do this?

**Comment by kr45732** [comment]
If you don't need SSL, you can remove `?sslmode` from the end of the Postgres database URL.

**Comment by UltimateBoi** [comment]
ah i see thank you

**Comment by UltimateBoi** [comment]
Also, it still crashes

**Comment by kr45732** [comment]
Did it crash with the same error or a different one?

**Comment by UltimateBoi** [comment]
same

**Comment by UltimateBoi** [comment]
![image](https://user-images.githubusercontent.com/63293118/146655641-a3a49e0a-302c-4761-a1c9-2670cd47f14b.png)

**Comment by UltimateBoi** [comment]
> Did it crash with the same error or a different one?

do you have discord? wut is ur tag? its easier on there.

**Comment by kr45732** [comment]
Yeah sure, you can join my discord: https://dsc.gg/skyblock-plus

**Comment by UltimateBoi** [comment]
im in it

**Comment by kr45732** [comment]
Resolved in DMs

**Comment by UltimateBoi** [comment]
Fixed ty
